// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace ErrorSceneLessNamespace {
  export interface IErrorSceneLess {
    wrapper: string
  }
}

declare const ErrorSceneLessModule: ErrorSceneLessNamespace.IErrorSceneLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ErrorSceneLessNamespace.IErrorSceneLess
}

export = ErrorSceneLessModule
