// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace ButtonLessNamespace {
  export interface IButtonLess {
    button: string
  }
}

declare const ButtonLessModule: ButtonLessNamespace.IButtonLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonLessNamespace.IButtonLess
}

export = ButtonLessModule
