/* eslint-disable @typescript-eslint/no-var-requires */
const customWebpackConfig = require('../web/webpack.config.js')
const path = require('path')

module.exports = {
  stories: ['../../packages/**/*.stories.mdx', '../../packages/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.less$/,
      use: [
        'style-loader',
        {
          loader: '@teamsupercell/typings-for-css-modules-loader',
          options: {
            banner: '// Autogenerated during build phase.\n// Any changes you make to this file will be overwritten.'
          }
        },
        {
          loader: 'css-loader',
          options: {
            modules: true,
            sourceMap: true
          }
        }
      ],
      include: path.resolve(__dirname, '../../')
    })

    // Return the altered config
    return config
  }
}
