// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace SectionLessNamespace {
  export interface ISectionLess {
    section: string
    sectionColumn: string
  }
}

declare const SectionLessModule: SectionLessNamespace.ISectionLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SectionLessNamespace.ISectionLess
}

export = SectionLessModule
