// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace DefaultButtonLessNamespace {
  export interface IDefaultButtonLess {
    button: string
  }
}

declare const DefaultButtonLessModule: DefaultButtonLessNamespace.IDefaultButtonLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: DefaultButtonLessNamespace.IDefaultButtonLess
}

export = DefaultButtonLessModule
