// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace ProjectLessNamespace {
  export interface IProjectLess {
    image: string
  }
}

declare const ProjectLessModule: ProjectLessNamespace.IProjectLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProjectLessNamespace.IProjectLess
}

export = ProjectLessModule
