// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace JumbotronLessNamespace {
  export interface IJumbotronLess {
    jumbotron: string
  }
}

declare const JumbotronLessModule: JumbotronLessNamespace.IJumbotronLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: JumbotronLessNamespace.IJumbotronLess
}

export = JumbotronLessModule
