// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace HeaderLessNamespace {
  export interface IHeaderLess {
    active: string
    logo: string
    navbar: string
  }
}

declare const HeaderLessModule: HeaderLessNamespace.IHeaderLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderLessNamespace.IHeaderLess
}

export = HeaderLessModule
