// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace SpinnerLessNamespace {
  export interface ISpinnerLess {
    spin: string
    spinner: string
  }
}

declare const SpinnerLessModule: SpinnerLessNamespace.ISpinnerLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SpinnerLessNamespace.ISpinnerLess
}

export = SpinnerLessModule
