// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace SvgRendererLessNamespace {
  export interface ISvgRendererLess {
    scale: string
  }
}

declare const SvgRendererLessModule: SvgRendererLessNamespace.ISvgRendererLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SvgRendererLessNamespace.ISvgRendererLess
}

export = SvgRendererLessModule
