// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace StackNavigationLessNamespace {
  export interface IStackNavigationLess {
    children: string
  }
}

declare const StackNavigationLessModule: StackNavigationLessNamespace.IStackNavigationLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StackNavigationLessNamespace.IStackNavigationLess
}

export = StackNavigationLessModule
