// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace LoaderLessNamespace {
  export interface ILoaderLess {
    centered: string
    load7: string
    loader: string
  }
}

declare const LoaderLessModule: LoaderLessNamespace.ILoaderLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LoaderLessNamespace.ILoaderLess
}

export = LoaderLessModule
