// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace GlobalLessNamespace {
  export interface IGlobalLess {
    'page-container': string
  }
}

declare const GlobalLessModule: GlobalLessNamespace.IGlobalLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlobalLessNamespace.IGlobalLess
}

export = GlobalLessModule
