/* eslint-disable @typescript-eslint/no-var-requires */
const webpack = require('webpack')
const path = require('path')
const HtmlWebPackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')

const isDev = process.env.NODE_ENV === 'development'

/**
 * Root Path
 * @desc Constructs a valid path from the current project directory
 * @param args Path components
 * @returns Valid concatenated path
 */
const rootPath = (...args) => args.reduce((fullPath, pathComponent) => path.join(fullPath, pathComponent), process.cwd())

/**
 * HTML Webpack Plugin
 * @desc Configuration for building the HTML page
 * @note Some props are injected and some are configuration (rendering) settings
 */
const htmlPlugin = new HtmlWebPackPlugin({
  title: 'Isaac Mackle - Software Engineer',
  template: rootPath('index.html'),
  filename: 'index.html',
  meta: {
    viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no',
    description:
      'Software Engineer who is always looking to learn more. Front-end focused with experience in React, Typescript. Get to know me'
  },
  minify: {
    collapseWhitespace: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true
  }
})

const hotModulePlugin = new webpack.HotModuleReplacementPlugin()

const miniCssExtractPlugin = new MiniCssExtractPlugin({
  filename: '[name].css',
  chunkFilename: '[id].css'
})

/**
 * HTML Webpack Plugin
 * @desc Copy static files to be used in build
 */
const copyWebpackPlugin = new CopyWebpackPlugin({
  patterns: [
    {
      from: './assets/*',
      to: './assets/[name].[ext]'
    }
  ]
})

/**
 * Webpack Configuration
 */
module.exports = {
  entry: ['webpack/hot/dev-server', rootPath('app.tsx')],
  target: 'web',
  output: {
    path: rootPath('dist'),
    publicPath: './',
    filename: '[name]-[hash]-bundle.js',
    chunkFilename: '[name]-[hash].bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: {
          loader: 'ts-loader'
        },
        exclude: [/node_modules/]
      },
      {
        test: /\.less$/,
        use: [
          'style-loader',
          {
            loader: '@teamsupercell/typings-for-css-modules-loader',
            options: {
              banner: '// Autogenerated during build phase.\n// Any changes you make to this file will be overwritten.'
            }
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                mode: 'local',
                localIdentName: isDev ? '[path][name]__[local]' : '[hash:base64:12]'
              },
              sourceMap: true
            }
          },
          {
            loader: 'less-loader',
            options: {
              sourceMap: true
            }
          }
        ]
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader']
      },
      {
        test: /\.(jpe?g|png|gif)$/i,
        use: [
          {
            loader: 'file-loader?name=[name].[ext]?[hash]',
            options: {
              esModule: false
            }
          },
          {
            loader: 'image-webpack-loader',
            options: {
              mozjpeg: {
                progressive: true,
                quality: 65
              },
              // optipng.enabled: false will disable optipng
              optipng: {
                enabled: false
              },
              pngquant: {
                // eslint-disable-next-line no-magic-numbers
                quality: [0.65, 0.9],
                speed: 4
              },
              gifsicle: {
                interlaced: false
              }
            }
          }
        ]
      },
      {
        test: /\.svg$/,
        use: ['@svgr/webpack']
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: 'file-loader'
      }
    ]
  },
  plugins: [
    miniCssExtractPlugin,
    htmlPlugin,
    hotModulePlugin,
    copyWebpackPlugin,
    new webpack.WatchIgnorePlugin([/less\.d\.ts$/, /scss\.d\.ts$/]),
    new webpack.DefinePlugin({
      __DEV__: isDev
    })
  ],
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.less', '.scss', '.module.scss', '.css']
  },
  devServer: {
    publicPath: 'http://localhost:8000',
    contentBase: rootPath('public'),
    lazy: false,
    compress: true,
    open: true,
    historyApiFallback: true,
    port: 8000
  }
}
