// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace HomeSceneLessNamespace {
  export interface IHomeSceneLess {
    container: string
    heading: string
  }
}

declare const HomeSceneLessModule: HomeSceneLessNamespace.IHomeSceneLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeSceneLessNamespace.IHomeSceneLess
}

export = HomeSceneLessModule
