// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace FooterLessNamespace {
  export interface IFooterLess {
    footer: string
    links: string
  }
}

declare const FooterLessModule: FooterLessNamespace.IFooterLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FooterLessNamespace.IFooterLess
}

export = FooterLessModule
